# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04be8a182bd2e107dc7ea9dfb05debcda095c865e1ca2fdaa47e73c1b7adb31fabb5747f3da5e4faeebd5f5be9e575ce2f4e014ef22fe418bf97122638091009

test:
  secret_key_base: 00bfd29a2fb5bafeeb9396a7ea9b9939629574da6c23616cee6c69f2cd5f3568d170bade745e6b800168b90ce68878c404a80977502272f8b4931649543d9b0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
